CREATE ROLE humlab_admin WITH SUPERUSER;
CREATE ROLE sead_read;
CREATE ROLE sead_write;
CREATE ROLE querysead_owner;
CREATE ROLE querysead_worker;
CREATE ROLE clearinghouse_worker;
CREATE ROLE sead_master;
CREATE ROLE humlab_read;
CREATE ROLE seadwrite;
CREATE ROLE postgrest;
CREATE ROLE postgrest_anon;
CREATE ROLE anonymous_rest_user;
CREATE ROLE mattias;
CREATE ROLE johan;
CREATE DATABASE sead WITH OWNER humlab_admin;
GRANT ALL PRIVILEGES ON DATABASE sead TO sead_write;
GRANT ALL PRIVILEGES ON DATABASE sead TO querysead_owner;
GRANT ALL PRIVILEGES ON DATABASE sead TO sead_master;
GRANT ALL PRIVILEGES ON DATABASE sead TO seadwrite;
